stages:
- stage: Init
  jobs:
  - job: Install
    steps:
    - script: echo install
  - job: install nano
    steps:
    - script: echo update
    steps:
    - script: echo test
- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!